# Generated by Django 5.1.4 on 2024-12-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="img")),
                ("desc", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("Мужское", "МУЖСКОЕ"), ("Женское", "ЖЕНСКОЕ")],
                        max_length=15,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
