# Generated by Django 5.1.4 on 2024-12-25 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="create_at",
        ),
        migrations.AddField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
